export const ENV = {
  APPWRITE_ENDPOINT: process.env.EXPO_PUBLIC_APPWRITE_ENDPOINT!,
  APPWRITE_PROJECT_ID: process.env.EXPO_PUBLIC_APPWRITE_PROJECT_ID!,
  APPWRITE_PLATFORM: process.env.EXPO_PUBLIC_APPWRITE_PLATFORM!,

  DB_ID: process.env.EXPO_PUBLIC_DB_ID!,
  DB_USERS_COL_ID: process.env.EXPO_PUBLIC_DB_USERS_COL_ID!,
  DB_PRODUCTS_COL_ID: process.env.EXPO_PUBLIC_DB_PRODUCTS_COL_ID!,
  DB_CART_ITEMS_COL_ID: process.env.EXPO_PUBLIC_DB_CARTITEMS_COL_ID!,

  BUCKET_ID: process.env.EXPO_PUBLIC_BUCKET_ID!,
};